### ISSUE TITLE
Building with 1.0.3 package has linking errors

### ISSUE THREAD

**Issue by jdm** [microsoft/OpenXR-SDK-VisualStudio#32]
When I tried upgrading the NuGet package in this project to the latest version, I received undefined symbols when linking for all of the extension APIs (eg. xrGetD3D11GraphicsRequirementsKHR).

**Comment by brycehutchings** [comment]
The loader does not export extension functions starting with 1.0.3. We've held off upgrading because the loader also has a bug which causes it to crash when using XrSpace handle created from an extension function (the spatial anchor extension). Hopefully the 1.0.6 or 1.0.7 loader will have the fix for this. This is why we've held off upgrading to the newer NuGet version. 

FYI, once the change goes in to fix the problem in the loader (https://github.com/KhronosGroup/OpenXR-SDK-Source/pull/146) it will only support a single XrInstance at a time.

**Comment by brycehutchings** [comment]
Apps will be required to use xrGetInstanceProcAddr to get function pointers for extension functions instead of statically linking to the loader. In the future we'll probably add some helper code to make this easier, something like GLEW.

**Comment by rpavlik** [comment]
(You can already use OpenXR-HPP which has exactly such a dispatch-table helper integrated in its design)

**Comment by yl-msft** [comment]
Upgraded to loader 1.0.6, which contains fix for the above issue.  See #33 for details.
